config/routes.rb
DayMan::Application.routes.draw do

  root to: 'home#homepage'

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :users, except: [:create, :update] do
    collection do
      post :import
      post :create_user
      post :update_user
      post :id_for_edit
    end
  end

  resources :schedules ,except: [:show, :index] do
    collection do
      get 'update_schedule'
    end
  end

  resources :subjects ,except: [:show]
  resources :branches
  resources :semesters

  post 'schedules/initialize_subjects', :to => 'schedules#initialize_subjects'
 
  get '/home', to: 'home#index'

  get '/admin', to: 'admin#index'

  get '/admin/subjects', to: 'subjects#index'

  get '/admin/schedules' , to: 'schedules#index'

  get '/admin/branches', to: 'branches#index'

  get '/admin/semesters', to: 'semesters#index'

  get '/admin/users', to: 'users#select_options'

  get '/import', to: 'users#import_users'
  
  get '/get_user_id', to: 'users#get_user_id'

end

app/models/user.rb
require 'iconv'

class User < ActiveRecord::Base

 # after_create :email_to_user
  before_create :set_default_role

  devise :database_authenticatable, :registerable,:recoverable,:validatable, :rememberable, :trackable #,:timeoutable

  belongs_to :role
  belongs_to :batch
  has_many :schedules

  #To Upload a Profile Avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :email, :presence => true
  validates_email_realness_of :email
 # validates :name, :presence => true
  

  def self.validate_new_user(user)
    t = "true"
    if user.name.nil? || user.email.nil? || user.role_id.nil?
      if user.name ==""
        t="Name"
      elsif user.email==""
        t="Email"
      elsif user.role_id.nil?
        t="Role"
      else
       t= "true"
      end
    end
    return t
  end

  def self.validate_user(name,role_id)
    $t="true"
    if name == "" || role_id == ""
      if name ==""
        $t="Name"
      elsif role_id == ""
        $t="Role"
      else
       $t= "true"
      end
    end
    return $t
  end

  def self.save_event_to_display(current_user)
    if current_user.role.name == "professor"
      data=Schedule.find_all_by_user_id(current_user.id)
      data.each do |d|
        d.name= d.subject.name+" for "+d.batch.name+" in "+d.room.name  #FULCALENDAR TITLE FOR PROFESSOR
        d.save!
      end
    elsif current_user.role.name == "student_professor"
      data=Schedule.find_all_by_batch_id_and_semester_id_and_branch_id(current_user.batch_id,current_user.semester_id,current_user.branch_id)
      data.each do |d|
        d.name= d.subject.name+" by "+d.user.name+" in "+d.room.name  #FULCALENDAR TITLE FOR STUDENT
        d.save!
      end
      professor_data=Schedule.find_all_by_user_id(current_user.id)
      professor_data.each do |d|
        d.name= d.subject.name+" for "+d.batch.name+" in "+d.room.name  #FULCALENDAR TITLE FOR PROFESSOR
        d.save!
        data.append(d);
      end
    else
      data=Schedule.find_all_by_batch_id_and_semester_id_and_branch_id(current_user.batch_id,current_user.semester_id,current_user.branch_id)
      data.each do |d|
        d.name= d.subject.name+" by "+d.user.name+" in "+d.room.name  #FULCALENDAR TITLE FOR STUDENT
        d.save!
      end
    end
    return data
  end

  #To create a user
  def self.create(user)
    user.save!
  end

  #To import a file :-
  def self.import(file)
    if open_spreadsheet(file) != false
      spreadsheet = open_spreadsheet(file)
    # spreadsheet = Roo::Excelx.new(file.path, nil, :ignore)
      header = spreadsheet.row(1)
      $error_array = []
      $error_count = 0
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        user = find_by_id(row["id"]) || new
        user.id = row['id']
        user.name = row['name']
        user.email = row['email']
        user.password = "12345678"
        user.role_id = row['role_id']
        user.batch_id = row['batch_id']
        user.semester_id = row['semester_id']
        user.branch_id = row['branch_id']
        user.sign_up_count = "1"
        if !user.email.nil? && !user.name.nil?
          begin
          ex=EmailVerifier.check(user.email)
          rescue => ex
            ex = false
          end
          if ex == true
            if user.valid?
              if user.role_id.to_s < "4" && !user.role_id.nil? && user.role_id.to_s != "0"
                if User.exists?(user.id)
                  if user.email == User.find(user.id).email && user.name == User.find(user.id).name
                    if user.email == User.find(user.id).email
                      user.save!
                    else
                      $error_array.append([i, "Email Address Can NOT Be Changed!"])
                      $error_count = $error_count + 1
                    end
                  else
                    $error_array.append([i, "ID Taken- Please assign a new ID!"])
                    $error_count = $error_count + 1
                  end
                else
                  user.save!
                  UserMailer.welcome_email(user).deliver
                end
              else
                if user.role_id.to_s > "3" || user.role_id.to_s == "0"
                  $error_array.append([i, "Invalid Role_id! Must be Between 1 to 3"])
                  $error_count = $error_count + 1
                end
                if user.role_id.nil?
                  $error_array.append([i, "Role_id Can NOT Be Empty!"])
                  $error_count = $error_count + 1
                end
              end
            end
          else
            $error_array.append([i, "Invalid Email Address!"])
            $error_count = $error_count + 1
          end
        else
          if !user.email?
            $error_array.append([i, "Email Can NOT Be Empty/NULL!"])
            $error_count = $error_count + 1
          else
            $error_array.append([i, "Name Can NOT Be Empty/NULL!"])
            $error_count = $error_count + 1
          end
        end
      end
      if $error_count > 0
        return false
      else
        return true
      end
    else
      return false
    end
  end

  def self.get_errors
    return $error_array
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path, packed: nil, file_warning: :ignore)
    when ".xls" then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
    else
      return false
    end
  end

  def original_filename
    return File.extname
  end

  private
 #Set Default Role as "user"
  def set_default_role
    self.role ||= Role.find_by_name('user')
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

 # before_filter :check_permissions, :only => [:new, :create, :cancel]

#  skip_before_filter :require_no_authentication

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @schedule = Schedule.new
    id=current_user.id
    @user=User.find(id)
    @data = User.save_event_to_display(current_user)
    respond_to do |format|
      format.html
      format.json { render :json => @data }
    end
  end

  def show
    @user = current_user
    @schedule = Schedule.new
    @professor = User.find_all_by_role_id(2)
    @branch =Branch.all
    @semester = Semester.all
    @batch = Batch.all
    @room = Room.all
    @subjects = Subject.all
    @data = User.save_event_to_display(current_user)  
    respond_to do |format|  
      format.html
      format.json { render :json => @data }  
    end 
  end

  def import
    if params[:file]
      if User.import(params[:file])
        flash[:success] = "Uploaded"
        redirect_to admin_users_path
      else
        if User.open_spreadsheet(params[:file]) == false
          flash[:error] = "Unknown file type!! Only .xls .xlsx .csv allowed!"
          redirect_to :back
        else
          flash[:error] = "Some error occured! Please try again!"
          @errors=User.get_errors
          session[:errors]=User.get_errors
          redirect_to :back
        end
      end
    else
      flash[:error] = "Choose a file to import!"
      redirect_to :back
    end
  end

  def new
    @user=User.new
    @roles = Role.all
    @semester = Semester.all
    @batch = Batch.all
    @branch = Branch.all
  end

  def create_user
    @user=User.new(user_params)
    error= User.validate_new_user(@user)
    if error == "true"
      @user.password = "12345678"
      @user.sign_up_count = "1"
      if @user.valid?
        @user.save!
        UserMailer.welcome_email(@user).deliver
        flash[:success] = "Created a New User!"
      redirect_to admin_users_path
      else
        if error != "true"
          flash[:error]="Enter "+error
          flash[:error] = "User not created."
        end
        redirect_to new_user_path
      end
    else
      flash[:error]="Enter "+error+"!"
      redirect_to new_user_path
    end
  end

  def id_for_edit
    user_id=params[:user_id]
    if user_id == ""
      flash[:error] = "Enter an ID to edit!"
      redirect_to :back
    elsif !User.find_by_id(user_id)
      flash[:error] = "Enter a VALID ID to edit!"
      redirect_to :back
    else 
      @user=User.find_by_id(user_id)
      redirect_to edit_user_path(@user)
    end
  end

  def edit
    @user = User.find(params[:id])
    @roles = Role.all
    @semester = Semester.all
    @batch = Batch.all
    @branch = Branch.all
  end

  def update_user
    @user = User.find(params[:user][:id])
    error=User.validate_user(params[:user][:name],params[:user][:role_id])
    if error == "true"
      if @user.update_attributes!(user_params)
        flash[:success] = "Updated User "+@user.name
        redirect_to get_user_id_path
      else
        flash[:error] = "User not updated."
      end
    else
      flash[:error]=error+" can not be left empty!"
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    flash[:success] = "Deleted User "+@user.name
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:id,:role_id,:batch_id,:semester_id,:branch_id)
  end

  $error_array = Array.new()

end

app/views/users/_form.html.erb
<html>
  <head>
      <title>s</title>
  </head>
  <body>
    <div id="dialog" title="Enter Event Details">
      <%= form_for(schedule, :remote => true, :format => :json) do |s| %>
        </p>
        <table width="70%">
          <tr>
            <td> <p style="text-align:right;">Start Time : </p></td>
            <td width="5%"></td>
            <td><p style="text-align:left;"><span id="startTime"></span></p></td>
          </tr>
          <tr>
            <td><p style="text-align:right;"> End Time : </p></td>
            <td width="5%"></td>
            <td><p style="text-align:left;"><span id="endTime"></span></p></td>
          </tr>
          <tr>
            <td><p style="text-align:right;">Professor : </p></td>
            <td width="5%"></td>
            <td><p style="text-align:left;"><%= user.name %> <span id="user_id"><%= user.id %></span></p></td>
          </tr>
          <tr>
            <td>
              <p style="text-align:right;">Branch : </p>
              <% branch_array = branch.map { |b| [b.name, b.id] } %>
            </td>
            <td width="5%"></td>
            <td width="60%">
              <%= s.select(:branch_id, options_for_select(branch_array),{include_blank: true},{:class => 'form-control'}) %> 
            </td>
          </tr>
          <tr>
            <td>
              <p style="text-align:right;">Semester : </p>
              <% semester_array = semester.map { |b| [b.name, b.id] } %>
            </td>
            <td width="5%"></td>
            <td width="60%">
              <%= s.select(:semester_id, options_for_select(semester_array), { include_blank: true } ,{:class => 'form-control'} ) %>
            </td>
          </tr>
          <tr>
            <td>
              <p style="text-align:right;">Subject : </p>
              <% subject_array = subjects.map{ |b| [b.name.to_s, b.id.to_i] } %>
            </td>
            <td width="5%"></td>
            <td width="60%">
              <%= s.select(:subject_id, options_for_select(subject_array),{ include_blank: true},{:class => 'form-control'}) %>
            </td>
          </tr>
          <tr>
            <td>
              <p style="text-align:right;">Room No. : </p>
              <% room_array = room.map { |b| [b.name, b.id] } %>
            </td>
            <td width="5%"></td>
            <td width="60%">
              <%= s.select(:room_id , options_for_select(room_array), { include_blank: true },{:class => 'form-control'}) %>
            </td>
          </tr>
        </table>
        <table>
          <tr>
            <td width="46%"><p style="text-align:right;">For Batches: </p></td>
            <td width="5%"></td>
            <% batch.each do |batch| %>
              <td><%= check_box_tag 'batch_ids[]', batch.id, :id => "batch_checkbox" %></td>
              <td><%= batch.name %></td>
              <td width="5%"></td>
            <% end %>   
          </tr>
        </table>
        <table>
          <tr>
            <td width="28%"><p style="text-align:right;">Repeat : </p></td>
            <td width="4%"></td>
            <td><%= radio_button_tag 'period', 0 %></td><td>Today</td><td width="4%"></td>
            <td><%= radio_button_tag 'period', 1 %></td><td>Daily</td><td width="4%"></td>
            <td><%= radio_button_tag 'period', 2 %></td><td>Weekly</td><td width="4%"></td>
            <td><%= radio_button_tag 'period', 3 %></td><td>Monthly</td><td width="4%"></td>
          </tr>
        </table>
        <table>
        <tr>
            <td width="40%" style="text-align:right;"><p style="text-align:right;">Start Date : </p></td>
            <td width="4%"></td>
            <td><%= s.date_select(:start_date) %></td>
          </tr>
          <tr>
            <td width="40%" style="text-align:right;"><p>End Date : </p></td>
            <td width="4%"></td>
            <td><%= s.date_select(:end_date) %></td>
          </tr>
        </table>

        <div class="row">
          <div class="col-md-12">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
              <input type="button" id="schedule_create" value="Create" class ='form-control'> 
              <input type="button" id="schedule_update" value="Update" class ='form-control'> 
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <br />
  </body>
</html>

app/views/users/edit.html.erb
<html>
  <head>
    <title>User</title>
  </head>
  <body>
	  <br/>
	  <br/>
			
		<div align="center" style="width:500px; height:200px" class="user_form">
				<h1>Editing  <span style="color:#FF7052"><%= @user.name %>'s</span>  Details</h1>
		<%= form_for @user, url: update_user_users_path(@user), method: 'post' do |u| %>
			    <div class="input" style="text-align:left">
			    	<b>Name</b><%= u.text_field :name %>
			    </div>
			    <div class="input" style="text-align:left">
			    	<b>Email</b><%= u.email_field :email, :readonly => true  %>
			    </div>
			    <div class="input" style="text-align:left">
			    	<b>ID</b><%= u.text_field :id, :readonly => true %>
			    </div>
			    <div style="text-align:left">
					  <div class="input">
						  <b>Role</b><% role = @roles.map{ |b| [b.name.to_s, b.id.to_i] } %>
						  <%= u.select(:role_id, options_for_select(role, selected: @user.role_id ),{ include_blank: true},{:class => 'form-control'}) %>
			      </div>
			      <div class="input" >
			    		<b>Batch</b><% batch = @batch.map{ |b| [b.name.to_s, b.id.to_i] } %>
			        <%= u.select(:batch_id, options_for_select(batch, selected: @user.batch_id),{ include_blank: true},{:class => 'form-control'}) %>
			      </div>
			      <div class="input" >
			    		<b>Semester</b><% semester = @semester.map{ |b| [b.name.to_s, b.id.to_i] } %>
			        <%= u.select(:semester_id, options_for_select(semester, selected: @user.semester_id),{ include_blank: true},{:class => 'form-control'}) %>
			      </div>
			      <div  class="input" >
						  <b>Branch</b><% branch = @branch.map{ |b| [b.name.to_s, b.id.to_i] } %>
						  <%= u.select(:branch_id, options_for_select(branch, selected: @user.branch_id),{ include_blank: true},{:class => 'form-control'}) %>
			      </div>
			    </div>
			    <br />
					<div style="text-align:left">
						<div style="float:left; width:500px;"> 
						  <%= u.submit %>
						</div>

			  <% end %>
						<div style="text-align: center;"><b>Or?</b></div>
						<div style="float:rigth;"> 
							<%= button_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }%>
						</div>
					</div>
		</div>
  </body>
</html>

app/views/users/get_user_id.html.erb
<div class="user_container">
	<br />
	<%= form_tag id_for_edit_users_path, method: :post do %>
		<div class="get_id">
			<table width="90%">
				<tr>
					<td width="30%">
						<b>Enter User ID : </b>
					</td>
					<td style="text-align:left;">
						<div class="input">
							<%= text_field_tag 'user_id' %>
						</div>
					</td>
					<td width="40%"><%= submit_tag 'Edit User', :id => "edit_user" ,:id => "button_new" %></td>
				</tr>
			</table>
		</div>
	<% end %>
</div>

app/views/users/import_users.html.erb
<html>
	<body>
		<div class="user_container">
			<br />
			<table width="75%">
				<tr>
					<%= form_tag import_users_path, multipart: true do %>
						<td style="text-align:right;"><b>Choose a file to import users.. :  </b></td>
						<td style="text-align:center;"><%= file_field_tag :file %></td>
						<td style="text-align:left;" ><%= submit_tag "Import!", :id => 'button_new' %></td>
					<% end %>
				</tr>
			</table>
      <br />
			<div style="text-align:center">
				<% if session[:errors] %>
					<h2>
				    <%= pluralize(session[:errors].length, "error")%>
				    prohibited this file from being uploaded:  
				  </h2>
					<p>There were problems with the following rows :</p>
	        <p>
	          <ul>
	            <% session[:errors].each do |row| %>
	              <li><b>Row <%= row[0] %></b> has the following problem: <b><%= row[1] %></b></li>
	            <% end %>
	          </ul> 
	        </p>
	        <% session[:errors] = nil %>
	      <% end %>
	    </div>
		</div>
	</body>
</html>

app/views/users/index.html.erb
<html>
	<body>
		<div class="user_schedule">
			<div><h1>Hello <%= @user.name %>!!</h1></div>
			<div>
				<ul>
					<li id="professor">
						<%= button_to 'Show table', user_path(@user) , method: :get %>
					</li>
				</ul>
			</div>
		</div>
	</body>
</html>

app/views/users/new.html.erb
<html>
  <head>
	<title>User</title>
  </head>
  <body>
  <div>
		<div align="left" style="width:500px; height:200px" class="user_form">
			<h1>Enter User Details :</h1>
			<%= form_for @user,url: create_user_users_path, method: 'post' do |u| %>
				<div class="input" style="text-align:left">
					<b>Name</b><%= u.text_field :name %>
				</div>
				<div class="input" style="text-align:left">
					<b>Email</b><%= u.email_field :email %>
				</div>
				<div class="input" style="text-align:left">
					<b>ID</b><%= u.text_field :id %>
				</div>
				<div style="text-align:left">
					  <div class="input">
						  <b>Role</b><% role = @roles.map{ |b| [b.name.to_s, b.id.to_i] } %>
						  <%= u.select(:role_id, options_for_select(role, selected: @user.role_id ),{ include_blank: true},{:class => 'form-control'}) %>
				  </div>
				  <div class="input" >
						<b>Batch</b><% batch = @batch.map{ |b| [b.name.to_s, b.id.to_i] } %>
					<%= u.select(:batch_id, options_for_select(batch, selected: @user.batch_id),{ include_blank: true},{:class => 'form-control'}) %>
				  </div>
				  <div class="input" >
						<b>Semester</b><% semester = @semester.map{ |b| [b.name.to_s, b.id.to_i] } %>
					<%= u.select(:semester_id, options_for_select(semester, selected: @user.semester_id),{ include_blank: true},{:class => 'form-control'}) %>
				  </div>
				  <div  class="input" >
						  <b>Branch</b><% branch = @branch.map{ |b| [b.name.to_s, b.id.to_i] } %>
						  <%= u.select(:branch_id, options_for_select(branch, selected: @user.branch_id),{ include_blank: true},{:class => 'form-control'}) %>
				  </div>
				</div>
				<br />
			<%= u.submit :class => 'form-control' %>
		  <% end %>
		</div>
		</div>
  </body>
</html>

app/views/users/select_options.html.erb
<html>
	<body>
		<div class="user_container">
			<br />
			<table width="90%">
				<tr>
					<td width="7%"></td>
					<td>
					<div class="circleBase type1">
					<br />
						<%= link_to image_tag('user2-add-icon.png'), new_user_path, method: :get %>
						</div>
					</td>
					<td width="7%"></td>
					<td>
					<div class="circleBase type2">
					<br />
						<%= link_to image_tag('user2-edit-icon.png'), get_user_id_path %>
					</div>
					</td>
					<td width="7%"></td>
					<td>
					<div class="circleBase type3">
					<br />
						<%= link_to image_tag('Add-File-icon.png'), import_path %>
					</div>
					</td>
				</tr>
			</table>
		</div>
	</body>
</html>

app/views/users/show.html.erb
<html>
	<head>
		<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
		<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
		<% if current_user.role_id == 2 %>
			<%= javascript_include_tag "professor_show_table.js" %>
		<% else %>
			<%= javascript_include_tag "show_calendar_user.js" %>
		<% end %>
	</head>
	<body>
		<div class="user_schedule">
		    <div class="greet_user"><div class="up"><br /><br /><br /><br /><br /><br /><br /><h1>Hello <%= @user.name %>!!</h1></div></div>
			<% if current_user.role_id == 2 %>
				<div  align="right" >
				    <%= button_to 'Notify Users', update_schedule_schedules_path, method: :get, :id => 'schedule_change' %>
					<br />
				</div>
			<% end %>
			<div id="calendar"></div>
			<% if current_user.role_id == 2 %>
				<%= render 'form', :user => @user, :schedule => @schedule , :branch => @branch , :subjects => @subjects , :semester => @semester, :room => @room, :batch => @batch %>
			<% end %>
		</div>
	</body>
</html>