config/routes.rb
DayMan::Application.routes.draw do

  root to: 'home#homepage'

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :users, except: [:create, :update] do
    collection do
      post :import
      post :create_user
      post :update_user
      post :id_for_edit
    end
  end

  resources :schedules ,except: [:show, :index] do
    collection do
      get 'update_schedule'
    end
  end

  resources :subjects ,except: [:show]
  resources :branches
  resources :semesters

  post 'schedules/initialize_subjects', :to => 'schedules#initialize_subjects'
 
  get '/home', to: 'home#index'

  get '/admin', to: 'admin#index'

  get '/admin/subjects', to: 'subjects#index'

  get '/admin/schedules' , to: 'schedules#index'

  get '/admin/branches', to: 'branches#index'

  get '/admin/semesters', to: 'semesters#index'

  get '/admin/users', to: 'users#select_options'

  get '/import', to: 'users#import_users'
  
  get '/get_user_id', to: 'users#get_user_id'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  belongs_to :branch
  belongs_to :semester
  belongs_to :subject
  belongs_to :user
  belongs_to :batch
  belongs_to :room

  delegate :name, :to => :subject, :prefix => true
  delegate :name, :to => :user, :prefix => true
  delegate :name, :to => :room, :prefix => true
  delegate :name, :to => :batch, :prefix => true
  delegate :name, :to => :branch, :prefix => true
  delegate :name, :to => :semester, :prefix => true

	validates :branch_id , presence: true
  validates :semester_id , presence: true
  validates :user_id , presence: true
	validates :subject_id , presence: true
 	validates :batch_id , presence: true
  validates :room_id , presence: true

  def self.update_schedule(schedule,batch_id,period,batch_ids,schedule_params,current_user)
    if schedule.valid?
      if period =="0" ||period.nil?
        schedule.update_attributes(schedule_params)
        Schedule.update_name_attribute(schedule)
      else
        if batch_ids.length > 1
          Schedule.create_updated_schedule(batch_ids,period,schedule_params,current_user,batch_id)
        else
          Schedule.create_updated_repeating_events(schedule_params,batch_id,period)
        end
      end
    end
  end

  def self.create_updated_repeating_events(schedule_params,b,period)
    schedule = Schedule.new(schedule_params)
    schedule.batch_id = b
    schedule.period = period
    $period = period
    $start = schedule.start_date
    $end = schedule.end_date
    if $start == $end
        $period = "0"
    end
    $start_time = schedule.starttime
    $end_time = schedule.endtime
    $day = "once"
    while $start<$end do
      schedule = Schedule.new(schedule_params)
      if $period == "1"
        schedule.start_date = schedule.start_date + 1.days
        schedule.starttime = $start_time + 1.days
        schedule.endtime = $end_time  + 1.days
        $start_time = $start_time + 1.days
        $end_time = $end_time + 1.days
        $start = $start + 1.days
        $day = "daily"
      elsif $period == "2"
        schedule.start_date = $start + 7.days
        schedule.starttime = $start_time + 7.days
        schedule.endtime = $end_time + 7.days
        $start_time = $start_time + 7.days
        $end_time = $end_time + 7.days
        $start = $start + 7.days
        $day = "weekly"
      else
        schedule.start_date = schedule.start_date + 28.days
        schedule.starttime = $start_time + 28.days
        schedule.endtime = $end_time + 28.days
        $start_time = $start_time + 28.days
        $end_time = $end_time + 28.days
        $start = $start + 28.days
        $day = "monthly"
      end
      if $start<=$end
        schedule.batch_id = b
        schedule.period = period
        if validate_professor_availability(schedule) && validate_room_availability(schedule) #&& !same_schedule(@schedule)
          if schedule.valid?
            schedule.name = schedule.subject_name+" by "+schedule.user_name+" in "+schedule.room_name+" for "+schedule.batch_name+"("+schedule.branch_name+")"
            schedule.save!
          end
        end
      end
    end
    $create_schedule_array.append([schedule,$day])
    #Schedule.update_create_schedule_array(schedule,$day)
  end

  def self.create_updated_schedule(batch_ids,period,schedule_params,current_user,current_batch_id)
    $day = "once"
    arr = batch_ids
    arr.each do |b|
      schedule = Schedule.new(schedule_params)
      schedule.batch_id = b
      schedule.period = period
      $period = period
      $start = schedule.start_date
      $end = schedule.end_date
      if $start == $end
        $period = "0"
      end
      $start_time = schedule.starttime
      $end_time = schedule.endtime
      if Schedule.validate_professor_availability(schedule) && Schedule.validate_room_availability(schedule) #&& !same_schedule(@schedule)
        if schedule.valid?
          schedule.name = schedule.subject_name+" by "+schedule.user_name+" in "+schedule.room_name+" for "+schedule.batch_name+"("+schedule.branch_name+")"
          if schedule.batch_id != current_batch_id
            schedule.save!
          end
          if $period == "0" || $period.nil?
            $create_schedule_array.append([schedule,$day])
          else
            Schedule.create_repeating_events(schedule_params,b,$period)
          end
        end
      else
        Schedule.error_display(schedule)
      end
    end
  end
  def self.create_schedule(batch_ids,period,schedule_params,current_user)
    $day = "once"
    arr = batch_ids
    arr.each do |b|
      schedule = Schedule.new(schedule_params)
      schedule.batch_id = b
      schedule.period = period
      $period = period
      $start = schedule.start_date
      $end = schedule.end_date
      if $start == $end
        $period = "0"
      end
      $start_time = schedule.starttime
      $end_time = schedule.endtime
      if Schedule.validate_professor_availability(schedule) && Schedule.validate_room_availability(schedule) #&& !same_schedule(@schedule)
        if schedule.valid?
          schedule.name = schedule.subject_name+" by "+schedule.user_name+" in "+schedule.room_name+" for "+schedule.batch_name+"("+schedule.branch_name+")"
          schedule.save!
          if $period == "0" || $period.nil?
            $create_schedule_array.append([schedule,$day])
          else
            Schedule.create_repeating_events(schedule_params,b,$period)
          end
        end
      else
        Schedule.error_display(schedule)
      end
    end
  end

  def self.error_display(schedule)
    if !Schedule.validate_professor_availability(schedule)
      flash[:error] = "That PROFESSOR is NOT AVAILABLE during that time!"
    elsif !Schedule.validate_room_availability(schedule) && !Schedule.validate_professor_availability(schedule)
      flash[:error] = "Professor and Room BOTH are NOT AVAILABLE!"
    else
      flash[:error] = "That ROOM is NOT AVAILABLE during that time!"
    end
  end

  def self.create_repeating_events(schedule_params,b,period)
    $day = "once"
    while $start<$end do
      schedule = Schedule.new(schedule_params)
      if $period == "1"
        schedule.start_date = schedule.start_date + 1.days
        schedule.starttime = $start_time + 1.days
        schedule.endtime = $end_time  + 1.days
        $start_time = $start_time + 1.days
        $end_time = $end_time + 1.days
        $start = $start + 1.days
        $day = "daily"
      elsif $period == "2"
        schedule.start_date = $start + 7.days
        schedule.starttime = $start_time + 7.days
        schedule.endtime = $end_time + 7.days
        $start_time = $start_time + 7.days
        $end_time = $end_time + 7.days
        $start = $start + 7.days
        $day = "weekly"
      else
        schedule.start_date = schedule.start_date + 28.days
        schedule.starttime = $start_time + 28.days
        schedule.endtime = $end_time + 28.days
        $start_time = $start_time + 28.days
        $end_time = $end_time + 28.days
        $start = $start + 28.days
        $day = "monthly"
      end
      if $start<=$end
        schedule.batch_id = b
        schedule.period = period
        if validate_professor_availability(schedule) && validate_room_availability(schedule) #&& !same_schedule(@schedule)
          if schedule.valid?
            schedule.name = schedule.subject_name+" by "+schedule.user_name+" in "+schedule.room_name+" for "+schedule.batch_name+"("+schedule.branch_name+")"
            schedule.save!
          end
        end
      end
    end
    $create_schedule_array.append([schedule,$day])
    #Schedule.update_create_schedule_array(schedule,$day)
  end

  def self.validate_professor_availability(schedule)
    schedule_all = Schedule.find_all_by_user_id(schedule.user_id)
    schedule_all.each do |s|
      if s.starttime.to_s == schedule.starttime.to_s && s.endtime.to_s == schedule.endtime.to_s && s.room_id.to_s != schedule.room_id.to_s
        return false
      else
        return true
      end
    end
  end

  def self.validate_room_availability(schedule)
    schedule_all = Schedule.find_all_by_room_id(schedule.room_id)
    schedule_all.each do |s|
      if s.starttime.to_s == schedule.starttime.to_s && s.endtime.to_s == schedule.endtime.to_s && s.user_id.to_s != schedule.user_id.to_s
        return false
      else
        return true
      end
    end
  end

  #when updating schedules
  def self.update_name_attribute(schedule)
    schedule.name = schedule.subject_name+" by "+schedule.user_name+" in "+schedule.room_name+" for "+schedule.batch_name+"("+schedule.branch_name+")"
    schedule.save!
  end

  def self.update_schedule_array(schedule)
    t = false
    $schedule_array.each do |s|
      if s.id == schedule.id
        $schedule_array.delete(s)
        $schedule_array.append(schedule)
        t = true
        break
      end
    end
    if t == false
      $schedule_array.append(schedule)
    end
  end

#  Not create if schedule is exactly the SAME!!  NOT WORKING!!!!!!!
#  def self.same_schedule(schedule)
#    schedule_all = Schedule.find_all_by_user_id_and_room_id(schedule.user_id, schedule.room_id)
#    schedule_all.each do |s|
#      if s.starttime.to_s == schedule.starttime.to_s && s.endtime.to_s == schedule.endtime.to_s
#        if s.batch_id == schedule.batch_id && s.branch_id == schedule.branch_id && s.semester_id == schedule.semester_id
#          return true
#        end
#      else
#        return false
#      end
#    end
#  end

  def self.send_email(role_id, schedule, create_schedule, delete_schedule)
    t= false
    if !create_schedule.nil?
      if Schedule.create_email(create_schedule, role_id)  
        t = true     
      else
        t = false
      end
    end
    if !schedule.nil?
      if Schedule.update_email(schedule, role_id)
        t = true
      else
        t = false
      end
    end
    if !delete_schedule.nil?
      if Schedule.delete_email(delete_schedule,role_id)
        t=true
      else
        t=false
      end
    end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	
  def new
    @branch_id_frmc = params[:branch_id]
    @semester_id_frmc = params[:semester_id]
    @batch_id_frmc = params[:batch_id]
    @schedule = Schedule.new
    @professor = User.find_all_by_role_id([2,4])
    @branch =Branch.all
    @semester = Semester.all
    @batch = Batch.all
    @room = Room.all
    @subjects = Subject.all
    @schedules = Schedule.find_all_by_batch_id_and_branch_id_and_semester_id( params[:batch_id], params[:branch_id], params[:semester_id])
    respond_to do |format|
      format.html
      format.json  { render :json => { :schedules => @schedules } }
    end
  end

  def initialize_subjects
    if !params[:branch_id].nil? && !params[:semester_id].nil? && !params[:batch_id].nil?
    @branch_id_frmc = params[:branch_id]
    @semester_id_frmc = params[:semester_id]
    @batch_id_frmc = params[:batch_id]
    branch_semester_subject = BranchSemesterSubject.find_all_by_branch_id_and_semester_id(params[:branch_id],params[:semester_id])
    @subjects = branch_semester_subject.collect! { |x| Subject.find(x.subject_id) }
    @schedule = Schedule.new
    @professor = User.find_all_by_role_id([2,4])
    @branch =Branch.all
    @semester = Semester.all
    @batch = Batch.all
    @room = Room.all
    @schedules = Schedule.find_all_by_batch_id_and_branch_id_and_semester_id( params[:batch_id], params[:branch_id], params[:semester_id])
    render :new
  else
    flash[:error]="Select Values!"
     render :new
  end
  end

  def create
    Schedule.create_schedule(params[:batch_ids],params[:period],schedule_params,current_user)
    respond_to do |format|
      format.html
      format.json {render :json => @schedule, :status => :created, :location => @schedule }
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render :json => @schedule }
    end
  end

  def update
    @schedule = Schedule.find(params[:id])
    $batch_id=@schedule.batch_id
    Schedule.update_schedule(@schedule,$batch_id,params[:period],params[:batch_ids],schedule_params,current_user)
    Schedule.update_schedule_array(@schedule)
    respond_to do |format|
      format.html
      format.json {render :json => @schedule }
    end
  end

# for when the schedule is changed and the mail needs to be sent
  def update_schedule
    role_id = current_user.role_id
    schedule = Schedule.get_schedule_array
    create_schedule = Schedule.get_create_schedule_array
    delete_schedule = Schedule.get_delete_schedule_array
    if Schedule.send_email(role_id,schedule,create_schedule,delete_schedule)
      flash[:success] = "Users Notified!"
      redirect_to root_path
    else
      flash[:error] = "Some error occured! Please try again!"
      redirect_to (:back)
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    Schedule.update_delete_array(@schedule)
    @schedule.destroy
    respond_to do |format|
      format.html
      format.json {render :json => @schedule }
    end
  end

  private
  def schedule_params
    params.require(:schedule).permit(:name, :branch_id, :semester_id, :user_id, :subject_id, :batch_id, :room_id, :starttime, :endtime, :start_date,  :end_date, :period, :batch_ids=>[])
  end
end

app/views/schedules/_form.html.erb
<html>
  <head>
    <title>Schedule</title>
  </head>
  <body>
    <div id="dialog" title="Enter Event Details">
      <%= form_for(schedule, :remote => true, :format => :json) do |schedule| %>
        <table width="70%">
          <tr>
            <td> <p style="text-align:right;">Start Time : </p></td>
            <td width="5%"></td>
            <td><p style="text-align:left;"><span id="startTime"></span></p></td>
          </tr>
          <tr>
            <td><p style="text-align:right;"> End Time : </p></td>
            <td width="5%"></td>
            <td><p style="text-align:left;"><span id="endTime"></span></p></td>
          </tr>
          <tr>
            <td>
              <p style="text-align:right;">Professor : </p>
              <% professor_array = professor.map { |b| [b.name, b.id] } %>
            </td>
            <td width="5%"></td>
            <td width="60%">
              <%= schedule.select(:user_id , options_for_select(professor_array),{include_blank: true},{:class => 'form-control'})%>
            </td>
          </tr>
          <tr>
            <td style="text-align:right;">
              <p>Subject : </p>
              <% subject_array = subjects.map{ |b| [b.name.to_s, b.id.to_i] } %>
            </td>
            <td width="5%"></td>
            <td width="60%">
              <%= schedule.select(:subject_id, options_for_select(subject_array),{ include_blank: true},{:class => 'form-control'}) %>
            </td>
          </tr>
          <tr>
            <td style="text-align:right;">
              <p>Room No. : </p>
              <% room_array = room.map { |b| [b.name, b.id] } %>
            </td>
            <td width="5%"></td>
            <td width="60%">
              <%= schedule.select(:room_id , options_for_select(room_array), { include_blank: true },{:class => 'form-control'}) %>
            </td>
          </tr>
        </table>
        <table>
          <tr>
            <td width="46%"><p style="text-align:right;">For Batches: </p></td>
            <td width="5%"></td>
            <% batch.each do |batch| %>
            <% if batch.id.to_s== batch_id_frmc.to_s %>
              <td><%= check_box_tag 'batch_ids[]', batch.id, true %></td>
            <% else %>
              <td><%= check_box_tag 'batch_ids[]', batch.id %></td>
            <% end %>
              <td><%= batch.name %></td>
              <td width="5%"></td>
            <% end %>   
          </tr>
        </table>
        <table>
          <tr>
            <td width="28%"><p style="text-align:right;">Repeat : </p></td>
            <td width="4%"></td>
            <td><%= radio_button_tag 'period', 0 %></td><td>Today</td><td width="4%"></td>
            <td><%= radio_button_tag 'period', 1 %></td><td>Daily</td><td width="4%"></td>
            <td><%= radio_button_tag 'period', 2 %></td><td>Weekly</td><td width="4%"></td>
            <td><%= radio_button_tag 'period', 3 %></td><td>Monthly</td><td width="4%"></td>
          </tr>
        </table>
        <table>
          <tr>
            <td width="40%" style="text-align:right;"><p style="text-align:right;">Start Date : </p></td>
            <td width="4%"></td>
            <td><%= schedule.date_select(:start_date) %></td>
          </tr>
          <tr>
            <td width="40%" style="text-align:right;"><p>End Date : </p></td>
            <td width="4%"></td>
            <td><%= schedule.date_select(:end_date) %></td>
          </tr>
        </table>
          
        <div class="row">
          <div class="col-md-12">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
              <div align="right">
                <input type="button" id="schedule_create" value="Create" class ='form-control'> 
                <input type="button" id="schedule_update" value="Update" class ='form-control'> 
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/schedules/_initialize_subjects_form.html.erb
<html>
  <body>
    <div>
      <table width="100%">
        <%= form_tag schedules_initialize_subjects_path, method: 'post' do %>
        <tr>
          <td style="color:#5a5a5a;"><b>Branch:</b></td>
          <td>
            <% branch_array = branch.map { |b| [b.name, b.id] } %>
            <%= select_tag(:branch_id, options_for_select(branch_array, selected: branch_id_frmc),{:class => 'form-control',prompt: 'Select Branch'}) %>
          </td>
          <td style="color:#5a5a5a;"><b>Semester:</b></td>
          <td>
            <% semester_array = semester.map { |b| [b.name, b.id] } %>
            <%= select_tag(:semester_id, options_for_select(semester_array, selected: semester_id_frmc), {:class => 'form-control',prompt: 'Select Semester'}) %>
          </td>
          <td style="color:#5a5a5a;"><b>Batch:</b></td>
          <td>
            <% batch_array = batch.map { |b| [b.name, b.id] } %>
            <%= select_tag(:batch_id, options_for_select(batch_array, selected: batch_id_frmc),{:class => 'form-control',prompt: 'Select Batch'}) %>
          </td>
          <td style="text-align:left;"><%= submit_tag "Apply" , :id => 'apply',:id =>'button_new',:class => 'form-control' %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </body>
</html>

app/views/schedules/new.html.erb
<html>
  <head>
    <title>Schedule</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <%= javascript_include_tag "new_form.js" %>

  </head>
  <body>
    <div class="initialize_subjects">
      <%= render 'initialize_subjects_form', :branch => @branch ,:semester => @semester, :batch => @batch,:branch_id_frmc => @branch_id_frmc ,:semester_id_frmc => @semester_id_frmc, :batch_id_frmc => @batch_id_frmc %>
    </div>
    <div class="calendar_container">
      <%= render 'form', :professor => @professor, :branch => @branch ,:semester => @semester, :room => @room, :batch => @batch, :subjects => @subjects, :schedule => @schedule, :batch_id_frmc => @batch_id_frmc %>
      <div align="right" >    
        <%= button_to 'Notify Users', update_schedule_schedules_path , method: :get , :id => 'schedule_change' %>
      </div>
      <br />
      <div id="calendar"></div>
    </div>
  </body>
</html>