config/routes.rb
DayMan::Application.routes.draw do

  root to: 'home#homepage'

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :users, except: [:create, :update] do
    collection do
      post :import
      post :create_user
      post :update_user
      post :id_for_edit
    end
  end

  resources :schedules ,except: [:show, :index] do
    collection do
      get 'update_schedule'
    end
  end

  resources :subjects ,except: [:show]
  resources :branches
  resources :semesters

  post 'schedules/initialize_subjects', :to => 'schedules#initialize_subjects'
 
  get '/home', to: 'home#index'

  get '/admin', to: 'admin#index'

  get '/admin/subjects', to: 'subjects#index'

  get '/admin/schedules' , to: 'schedules#index'

  get '/admin/branches', to: 'branches#index'

  get '/admin/semesters', to: 'semesters#index'

  get '/admin/users', to: 'users#select_options'

  get '/import', to: 'users#import_users'
  
  get '/get_user_id', to: 'users#get_user_id'

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :schedules
	has_many :branch_semester_subjects
	has_many :branches, :through => :branch_semester_subject
	has_many :semesters, :through => :branch_semester_subject

	validates :name , uniqueness: true , presence: true

	def self.destroy_and_create_BSS(bss,branches,semesters,subject_id)
		bss.each do |b|
			b.destroy
		end
		branches.each do |b|
			semesters.each do |s|
			bss=BranchSemesterSubject.new
				bss.branch_id = b
				bss.semester_id = s
				bss.subject_id = subject_id
				bss.save!
			end
		end
	end

	def self.create_BSS(bss,branches,semesters,subject_id)
		branches.each do |b|
			semesters.each do |s|
				bss=BranchSemesterSubject.new
				bss.branch_id = b
				bss.semester_id = s
				bss.subject_id = subject_id
				bss.save!
			end
		end
	end
end
 

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	def index
		@subjects = Subject.all
		@bss = BranchSemesterSubject.all
		@branch = Branch.all
		@semester = Semester.all
	end

	def new
		@subject = Subject.new
		@count = true
	end

	def create
		@subject = Subject.new(subject_params)
		@bss=BranchSemesterSubject.new
		branches=params[:branch_ids]
		semesters=params[:semester_ids]
		if !params[:branch_ids] || !params[:semester_ids]
			render 'new'
			flash[:error] = "Incomplete Information!!"
		else
			if @subject.valid?
				@subject.save!
				Subject.create_BSS(@bss,branches,semesters,@subject.id)
				redirect_to subjects_path
				flash[:success] = "Subject Created!"
			else
				render 'new'
				flash[:error] = "Incomplete Information!!"
			end
		end
	end

	def edit
		@subject = Subject.find(params[:id])
		@bss = BranchSemesterSubject.find_all_by_subject_id(params[:id])
		@count = false
	end

	def update
		@subject = Subject.find(params[:id])
		@bss = BranchSemesterSubject.find_all_by_subject_id(params[:id])
		branches=params[:branch_ids]
		semesters=params[:semester_ids]		
		if @subject.valid?
			@subject.update_attributes!(subject_params)
			Subject.destroy_and_create_BSS(@bss,branches,semesters,@subject.id)
			redirect_to subjects_path
		else
			render 'edit'
		end
	end

	def destroy
		@subject = Subject.find(params[:id])
		@BranchSemesterSubject = BranchSemesterSubject.find_all_by_subject_id(params[:id])
		@BranchSemesterSubject.each do |b|
			b.destroy
		end
		@subject.destroy
		redirect_to subjects_path
	end

	def subject_params
		params.require(:subject).permit(:name,:branch_semester_subject_ids => [])
	end
end

app/views/subjects/_form.html.erb
 <html>
 <head>
    <title>s</title>
    <script>
    $(document).ready(function()
    {
      var checkboxBatch = function()
      {
        var atLeastOneBranchIsChecked = $('#branch_ids_ input:checked').length > 0;
        if(!atLeastOneBranchIsChecked){ alert("Select a Branch!"); return false; }
        var atLeastOneSemesterIsChecked = $('#semester_ids_ input:checked').length > 0;
        if(!atLeastOneSemesterIsChecked){ alert("Select a Semester!"); return false;}
      }
    });
    </script>
  </head>

  <div>
    <%= form_for subject, :html => { :id => 'form' } do |s| %>
    <table>
    <tr><td><b>Name : </b></td><td><%= s.text_field :name %></td>
    </tr></table>
    <span style="color:red">
    <% if subject.errors[:name] %>
      <% a= subject.errors.full_messages_for(:name) %>
      <%= a.join(", ") %>
    <% end %>
    </span>

  <br />
  <br />
  <b>Branch :</b>
  <table>
    <tbody>
      <% Branch.all.each do |branch| %>
       <tr>
       <td>
          <% brArr = [] %>
          <% if count == false %>
          <% bss.each do |branchArray| %>
                <% if branchArray.branch_id == branch.id %>
                    <% brArr.push(branch.id) %>
                <%end%>
          <%end%>
          <% end %>
        <%= check_box_tag "branch_ids[]" , branch.id , brArr.include?(branch.id) %> 
        </td>
        <td>
        <label><%= branch.name %></label>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </span>
  <br />
  <br />
  <b>Semester :</b>
  <table>
    <tbody>
      <% Semester.all.each do |semester| %>
        <tr>
        <td>
          <% semArr = [] %>
          <% if count == false %>
          <% bss.each do |branchArray| %>
                <% if branchArray.semester_id == semester.id %>
                    <% semArr.push(semester.id) %>
                <%end%>
          <%end%>
          <% end %>
          <%= check_box_tag "semester_ids[]", semester.id, semArr.include?(semester.id) %>
        </td>
        <td> 
            <label><%= semester.name %></label>
      </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br />
  <br />
  <div align="left"><span id="submit"><%= s.submit %></span></divleft  <% end %>
  </div>

</html>

app/views/subjects/edit.html.erb
<div align="center">
<br />
<br />
<h1>Enter subject Details :</h1>
<%= render 'form', :subject => @subject ,:bss => @bss, :count => @count %>
</div>

app/views/subjects/index.html.erb
<html>
  <head><title>Subjects</title>
  </head>
  <body>
    <div class="subject_container">
      <div align="right" class="create_new_subjects">
        <%= button_to 'Create New' , new_subject_path , method: :get,:id=>'create_button_subjects', :class=>'form_control'%>
      </div>
      <div align="center">
        <table width="90%" style="font-size:20px" cellspacing="20">   
          <br />
          <br />
          <br />
          <tr>
          	<th width="28%"></th>
            <th width="30%"></th>
            <th width="30%"></th>
            <th width="6%"></th>
            <th width="6%"></th>
          </tr>
          <% @subjects.each do |subject| %>
            <tr>
            <td style="text-align:left;color:#5a5a5a;"><%= subject.name %></td>
            <td style="color:#black;text-align:center;">
            <% branchArray = Array.new %>
            <% c = 0 %>
            <% @bss.each do |branch| %>
                <% if branch.subject_id == subject.id %>
                    <% if !branchArray.include?(@branch.find(branch.branch_id).name) %>
                        <%branchArray.push(@branch.find(branch.branch_id).name) %>
                    <%end%>
                <% end %>
            <% end %>
            <% branchArray.each do |a| %>
                      <% if c==0 %>
                          <%= a %>
                          <% c=1 %>
                      <%else%>
                          , <%= a %>
                      <%end%>
                  <%end%>
            </td>
            <td style="color:#5a5a5a">
            <% semesterArray = Array.new %>
            <% c = 0 %>
            <% @bss.each do |semester| %>
                <% if semester.subject_id == subject.id %>
                    <% if !semesterArray.include?(@semester.find(semester.semester_id).name) %>
                        <%semesterArray.push(@semester.find(semester.semester_id).name) %>
                    <%end%>
                <% end %>
            <% end %>
            <% semesterArray.each do |a| %>
                      <% if c==0 %>
                          <%= a %>
                          <% c=1 %>
                      <%else%>
                          , <%= a %>
                      <%end%>
                  <%end%>
            </td>
            <td>
              <%= link_to image_tag('edit-icon.png'),edit_subject_path(subject) %>
            </td>
            <td style="text-align:left;"><%= link_to image_tag('Close-2-icon.png'),subject,method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
          <% end %>
        </table>
        <br />
      </div>
    </div>
  </body>
</html

app/views/subjects/new.html.erb
<div align="center">
<br />
<br />
<h1>Enter subject Details :</h1>
<%= render 'form', :subject => @subject, :bss => @bss, :count => @count %>
</div>