config/routes.rb
DayMan::Application.routes.draw do

  root to: 'home#homepage'

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :users, except: [:create, :update] do
    collection do
      post :import
      post :create_user
      post :update_user
      post :id_for_edit
    end
  end

  resources :schedules ,except: [:show, :index] do
    collection do
      get 'update_schedule'
    end
  end

  resources :subjects ,except: [:show]
  resources :branches
  resources :semesters

  post 'schedules/initialize_subjects', :to => 'schedules#initialize_subjects'
 
  get '/home', to: 'home#index'

  get '/admin', to: 'admin#index'

  get '/admin/subjects', to: 'subjects#index'

  get '/admin/schedules' , to: 'schedules#index'

  get '/admin/branches', to: 'branches#index'

  get '/admin/semesters', to: 'semesters#index'

  get '/admin/users', to: 'users#select_options'

  get '/import', to: 'users#import_users'
  
  get '/get_user_id', to: 'users#get_user_id'

end

app/views/layouts/_admin_options.html.erb
<div class="admin_fixed_options">
	<div class="fixed_options">
	  <table width="100%" >
	    <tr></tr><br />
	    <tr><%= link_to 'Branches', new_branch_path , id: "admin_a" %><br></tr>
	    <tr><%= link_to 'Schedules', new_schedule_path ,  id: "admin_a" %><br></tr>
	    <tr><%= link_to 'Semesters', new_semester_path ,  id: "admin_a"%><br></tr>
	    <tr><%= link_to 'Subjects', admin_subjects_path , method: :get , id: "admin_a" %><br></tr>
	    <tr><%= link_to 'Users', admin_users_path , method: :get , id: "admin_a" %><br></tr>
	  </table>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright © 2014 Tata Consultancy Services
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    
      <div id="logo"><%= link_to "Day Manager",root_url, id: "logo" %></div>
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <div id="links">
        <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to 'Home', root_url %></li>
              <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
              <li><%= link_to "Back", :back %></li>
            <% else %>
              <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
        </ul>
        </div>
      </div>
    
  </div>
</header>

app/views/layouts/_menu.html.erb
<div class="collapse navbar-collapse" id="navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to 'Posts', '#' %></li>
    <% if current_user %>
      <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
    <% else %>
      <li><%= link_to 'Login', new_user_session_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DayManager</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <% if user_signed_in? %>
    <div>
      <%= render 'layouts/header' %>
      </div>
    <% end %>

    <div align="center" class="alert_msgs">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
    
    <% if user_signed_in? %>
      <% if current_user.role_id == 1 %>
        <%= render 'layouts/admin_options' %>
      <% end %>
    <% end %>
    <div class="container" id="container">
      <%= yield %>
    </div>
  </body>
</html>